spring.application.name=apikitchen
# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/kitchenhack
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto
server.port=8080