spring.application.name=apikitchen
# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/kitchenhack
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
# Usa update para crear/ajustar tablas faltantes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto
server.port=8085
